### ISSUE TITLE
SteamDeck failed to install SimpleHeels

### ISSUE THREAD

**Issue by StarShadow09** [Caraxi/SimpleHeels#36]
hello, im not sure if im in the right spot for this, but ive been trying to download the simpleheels plugin, and it keeps telling me that it fails to install and to restart, which i have done many times, i have installed others and i still have plenty of space, i am not sure what to do from here.
i would really appreciate the help
Thank you
![Screenshot_20240504_130914](https://github.com/Caraxi/SimpleHeels/assets/168926973/5d685278-7658-4b65-b640-437304a72195)

**Comment by oz-orz** [comment]
Similar situation on Fedora 40, GNOME Wayland. Even though all other plugins I have tried were successfully installed, for whichever reason SimpleHeels refuses to be installed. It successfully installed at some prior point; however, I have had to refresh my Dalamud settings through XIVLauncher to fix problems with other things and now I can't install Simple Heels at all. I have removed all SimpleHeels-related files I could find from `~/.xlcore`. Issue persists.

In an attempt to remedy the issue, I have tried to add the personal Dalamud repo on the main page of this repo, but I cannot connect to the repo at all in Dalamud, which says that connection to ` https://repo.caraxian.com` failed.

It's quite possible that this issue is somehow related to SSH. FFXIV on Linux requires an SSH-related workaround in XIVLauncher, due to some outdated network configuration on Square Enix's part; perhaps this workaround is causing problems with connecting to SimpleHeels.

My `dalamud.log` is attached. This is a log from a session where I logged in, Dalamud and third party plugins enabled, tried to install SimpleHeels once, got the same error message, and quit the game through the main menu.

It might be worth looking into XIVLauncher's Linux SSH workaround, and if/how Dalamud and the Sea of Stars repo implement this (be it through source code itself or commits/issues on repos).

[dalamud.log](https://github.com/Caraxi/SimpleHeels/files/15211457/dalamud.log)

**Comment by Caraxi** [comment]
Its failing to create an SSL connection. Consult with people who know Linux because this isn't really something I can do anything about

**Comment by StarShadow09** [comment]
> Its failing to create an SSL connection. Consult with people who know Linux because this isn't really something I can do anything about

but if its the SSL connection, would i not be able to install the other plugins that are using the same repo? im able to install the other plugins like simpletweaks and honorific, this one is the only one for some reason its not installing

**Comment by Caraxi** [comment]
If you can access

https://repo.caraxian.com/ and https://repo.caraxian.com/plugins/SimpleHeels/0.9.3.0.zip then the install should be fine. The log says it is failing the SSL connection and is nothing I can do if you can't connect

**Comment by Caraxi** [comment]
Please try installing from this repo instead of the default
```
http://repo.caraxian.com/no_https.json
```

**Comment by XenHat** [comment]
**I can confirm that using your repo fixes the issue.**

_I can install other plugins from SeaOfStars just fine on my Linux desktop, so I'm not sure what is up with SimpleHeels' copy on that repo._
